git YoshiHotta/Brewfile
install adns
install apache-spark
install autoconf
install automake
install aws-elasticbeanstalk
install awscli
install brew-file
install bzip2
install cloc
install cmake
install coreutils
install cscope
install drone
install fontconfig
install fpp
install freetype
install fswatch
install gcc
install gd
install gdbm
install gettext
install git-lfs
install gmp
install gnupg
install gnutls
install go
install gpg-agent
install graphviz
install grep
install gzip
install hadoop
install icu4c
install imagemagick
install isl
install javarepl
install jenkins
install jpeg
install jq
install libassuan
install libevent
install libffi
install libgcrypt
install libgpg-error
install libksba
install libmpc
install libpng
install libssh
install libtasn1
install libtiff
install libtool
install libunistring
install libusb
install libxml2
install libxslt
install libyaml
install lua
install mackup
install macvim
install mas
install maven
install mpfr
install msgpack
install mysql
install nettle
install nkf
install nmap
install node
install npth
install oniguruma
install openssl
install p11-kit
install pcre
install peco
install pinentry
install pinentry-mac
install pkg-config
install postgresql
install protobuf@2.5
install pth
install pyenv
install pyenv-virtualenv
install python
install rbenv
install readline
install reattach-to-user-namespace
install rmtrash
install ruby
install ruby-build
install sbt
install scala
install snappy
install socat
install sqlite
install terraform
install tmate
install tmux
install tree
install unison
install vim
install webp
install wget
install xz
install zlib
